version: "3.8"

services:
  slowloris:
    image: '${DOCKER_IMAGE_PREFIX?Variable not set}slowloris:rolling'
    build:
      context: .
      dockerfile: dockerfiles/slowloris.dockerfile
      args:
        DOCKER_IMAGE_PREFIX: ${DOCKER_IMAGE_PREFIX?Variable not set}
    network_mode: "host"
    env_file:
      - ./.env

  tor:
    image: '${DOCKER_IMAGE_PREFIX?Variable not set}tor:rolling'
    build:
      context: .
      dockerfile: dockerfiles/tor.dockerfile
      args:
        DOCKER_IMAGE_PREFIX: ${DOCKER_IMAGE_PREFIX?Variable not set}
    network_mode: "host"
    env_file:
      - ./.env
